cordis-lib/cordis

- libs/rest/src/Bucket.ts
- libs/rest/src/Fetch.ts
- libs/rest/src/RestManager.ts
- libs/routers/src/IRouter.ts
closes #23 
Passes all Jest tests, lint, and builds.
> fix: add a RequestBodyData type and replace in appropriate areas

- libs/routers/src/IRouter.ts
- libs/routers/src/restRouter.test.ts
`IRouter` methods used to return `T`, but this is incorrect. An `IRouter` implementation will never be sync, this is HTTP we're talking about.
> fix(IRouter): return types

- .github/workflows/docs.yml
closes #28
adds `.github/workflows/docs.yml` which will follow these steps:
- Checkout repository
- Install Node v15
- Install pnpm
- Install deps
- Build the code
- Build the docs
- Commit the doc dir to the docs repo
> workflows: add docs deploy workflow

- libs/gateway/src/websocket/Cluster.ts
This PR fixes an issue where guild objects would've likely been kept as `[object Object]`, or however IORedis decided to handle the objects we were throwing at it.
> fix(Cluster): redis store construction

- .github/workflows/docs.yml
The docs are not currently avaliable at https://cordis.didinele.me due to an oversight that resulted in the CNAME file not being placed in the built docs before being pushed.
This PR will resolve that.
> emergency fix for docs deploy workflow

- libs/rest/src/Bucket.ts
- libs/rest/src/Fetch.ts
- libs/rest/src/RestManager.ts
- libs/routers/src/IRouter.ts
This issue was going to be fixed in #32 but that would only land in a minor release anyway, so better of getting it out this week.
> fix(rest/router): generic types for making requests

- libs/rest/src/RestManager.ts
At the current state, RestManager#post **requires** you to supply a file array.
It shouldn't.
made it optional 😄.
> fix: make options.files optional

- libs/common/src/functions/functions.test.ts
This PR fixes an issue with the test for the `halt` function, that would rely on actual non-mocked `setTimeout` and `Date.now`, causing inconsistent and unpredictable failure at random times.
> fix(functions/test): halt test can no longer randomly fail

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/meta_thread.md
- README.md
This PR adds a meta issue template and also fixes a few cheeky issues with the existing templates and new README.
- This PR **only** includes non-code changes, like changes to documentation, README, etc.
> feat(repo): meta thread issue template & other regressions

- README.md
- libs/bitfield/README.md
- libs/brokers/README.md
- libs/common/README.md
- libs/error/README.md
- libs/gateway/README.md
- libs/queue/README.md
- libs/redis-store/README.md
- libs/rest/README.md
- libs/routers/README.md
- libs/snowflake/README.md
- libs/store/README.md
- This PR **only** includes non-code changes, like changes to documentation, README, etc.
> replace cordis.didinele.me with cordis.js.org

- libs/redis-store/src/index.ts
Closes #22
This PR removes some methods that aren't necessary with the usage of pipelines.
Also, on second thought, there's nothing that the store can really implement in terms of pipelines. Just use `<RedisStore>.redis.pipeline()`.
NOTE: This change is not a patch - do NOT merge yet.
> chore: remove redundant methods from redis-store

- libs/util/src/restUtils.ts
This PR fixes a problem where `webhookIdOrToken` not being exported caused any usage of `makeRestUtils` to not compile.
- This PR changes the library's interface (methods or parameters added)
Semver things™:
- You would think that this is a breaking change due to the rename of `webhookIdOrToken`, however, not being exported, it was private, which would make this change an addition and therefore, minor.
- All though, without this change `makeRestUtils` is literally unusable, so I'm going to simply classify this as a patch change.
> fix(restUtil): weebhook data problems

- libs/util/package.json
- pnpm-lock.yaml
`discord-api-types` was apparently not declared as a dependency in `@cordis/util` leading to runtime errors when attempting to import it on package managers that don't use flat node_modules structures, or, in general, if it just wasn't installed from something else.
> fix(util): add discord-api-types dependency

- libs/rest/src/Error.ts
- libs/rest/src/Fetch.ts
- libs/rest/src/mutex/Mutex.ts
- libs/rest/src/mutex/RedisMutex.ts
- libs/rest/src/mutex/mutex.test.ts
- libs/rest/src/struct/Bucket.ts
- libs/rest/src/struct/Rest.ts
- libs/rest/src/struct/rest.test.ts
- fix(Bucket): actually throw on prevented ratelimits when retryAfterRatelimit is false
- fix(RedisMutex): handle TTLs for the remaining key correctly (see #72)
Closes #72 
- This PR changes the library's interface (methods or parameters added)
> chore: polish rest

- .versionrc.js
- CHANGELOG.md
- package.json
- pnpm-lock.yaml
This PR begins enforcing conventional commit messages and adds a way for one to automatically bump everything & commit it.
Do keep in mind we should still manually update inner-deps (ctrl+f for `workspace:^x.y.z`) and re-run `pnpm i` to make sure the lock file is up to date.
Running `pnpm run changelog "--" --other-options-here` (docs for options can be found [here](https://github.com/conventional-changelog/standard-version)) will do all the bumping, make a commit and a local tag.
Once you do that, make a seperate commit for all the deps/lockfile stuff, push it and open a PR - should be merged via squash with no body.
From here on out, PR merge commits should follow …
> chore: automatic changelog generation

- libs/brokers/src/brokers/pubsub/PubSubPublisher.ts
- libs/brokers/src/brokers/pubsub/PubSubSubscriber.ts
- libs/brokers/src/brokers/pubsub/pubsub.test.ts
- libs/brokers/src/brokers/routing/RoutingPublisher.ts
- libs/brokers/src/brokers/routing/RoutingSubscriber.ts
- libs/brokers/src/brokers/routing/routing.test.ts
- libs/brokers/src/brokers/rpc/RpcPublisher.ts
- libs/brokers/src/brokers/rpc/RpcSubscriber.ts
- libs/brokers/src/brokers/rpc/rpc.test.ts
- libs/brokers/src/index.ts
- services/gateway/src/index.ts
This PR changes the inconsistent and confusing "client/server" naming into "publisher/subscriber", more accurately depicting what each class does.
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
> refactor(Brokers): change confusing client/server naming to publisher/subscriber

- services/gateway/src/args.ts
This PR fixes a regression from #84 that caused env vars to be ignored by the gateway.
> fix(GatewayService): parse for env once again

- libs/bitfield/package.json
- libs/brokers/package.json
- libs/common/package.json
- libs/error/package.json
- libs/gateway/package.json
- libs/queue/package.json
- libs/redis-store/package.json
- libs/rest/package.json
- libs/store/package.json
- libs/util/package.json
- package.json
- pnpm-lock.yaml
- services/gateway/package.json
This PR moves `discord-api-types` into the runtime dependencies for `@cordis/rest`, as it was being used for constants - causing a hard crash.
> fix(rest): move discord-api-types into runtime deps

- libs/rest/README.md
Remove router references due to them being removed in #85 
- This PR **only** includes non-code changes, like changes to documentation, README, etc.
> chore: remove router references

- libs/rest/src/Fetch.ts
- libs/rest/src/struct/Rest.ts
This PR implements caching at the Rest class level, removing the need for a lot of awkward caching implementations I've built on the bot-level.
- This PR changes the library's interface (methods or parameters added)
> feat(Rest): caching support
